name: sbom-test
on:
  push:
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - name: Install tool
        run: pip install cyclonedx-bom 
      - name: Generate BOM
        id: sbom
        run: |
             cyclonedx-py --poetry --format xml -o sbom.xml
             
      - name: Submit SBOM
        run: |
          curl -k -X POST "https://dt-api.staging.cryptosoft.com/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key:1DMIXAnGtTIeTQDddlHSvpj6d3as174S" \
            -F "autoCreate=true" \
            -F "projectName=Testjuly11" \
            -F "projectVersion=1.8" \
            -F "parentName=Testproject3" \
            -F "parentVersion=1.0.2" \
            -F "bom=@sbom.xml"
